### ISSUE TITLE
Recreate NavBar

### ISSUE THREAD

**Issue by srivastavaritik** [srivastavaritik/Extraspace-Cloud#7] opened 2022-09-30 19:17 UTC
![image](https://user-images.githubusercontent.com/78131705/193341246-7b5c4412-3861-493d-b01f-36a90c80e56d.png)
**Make an atttractive Navbar**

**Comment by raji2004** [comment] 2022-10-01 00:06
i would love to be assigned this issue

**Comment by srivastavaritik** [comment] 2022-10-01 03:44
Okay, I am assigning you this task.

**Comment by raji2004** [comment] 2022-10-01 08:51
can i  restyle the page?

**Comment by srivastavaritik** [comment] 2022-10-01 09:53
> can i restyle the page?

okay, but make login card is already assigned to someone, so you can work on rest, like the background, navbar and the footer.

**Comment by srivastavaritik** [comment] 2022-10-03 03:57
@raji2004 Are you working on this?

**Comment by raji2004** [comment] 2022-10-03 05:45
Yes I am

**Comment by hs-07** [comment] 2022-10-04 14:59
@srivastavaritik 
hey!
I went through the project, and if i tell from the user point of view, it wasnt seems that appealing but the concept and working of the application is really very nice.
I would like to contribute to the project with my set of skills.
So, if the issue is still open and the I wanted you to assign it to me, for immediate updations on the site
Thankyou

**Comment by srivastavaritik** [comment] 2022-10-04 15:11
hi @hs-07 ,
Glad to know that you are interested in this project, it has already been 3 days since @raji2004 has taken this issue, if he will not be able to solve this by tomorrow noon, then I will assign you this task. Since then you can have a look at the forgot password page as its styling is not done goodly.

**Comment by hs-07** [comment] 2022-10-05 18:21
hey @srivastavaritik 
assign the issue to me,.... i will resolve it

**Comment by hs-07** [comment] 2022-10-06 10:30
> hi @hs-07 , Glad to know that you are interested in this project, it has already been 3 days since @raji2004 has taken this issue, if he will not be able to solve this by tomorrow noon, then I will assign you this task. Since then you can have a look at the forgot password page as its styling is not done goodly.

@srivastavaritik 
Now can, you assign it to me?

**Comment by srivastavaritik** [comment] 2022-10-06 16:33
@hs-07 i think you are doing this in issue #30 ??

**Comment by hs-07** [comment] 2022-10-06 17:03
yaa

**Comment by hs-07** [comment] 2022-10-08 09:50
@srivastavaritik 
Why my today's commit in repo isnt reflected on the main link of website??

**Closed** 2022-12-18 04:55 UTC
Labels: good first issue, hacktoberfest, hacktoberfest2022, open, unassigned
